### ISSUE TITLE
Change shown date format

### ISSUE THREAD

**Issue by henneho** [isabellaalstrom/lovelace-grocy-chores-card#62]
Hey

I'd love to have the possibility to change the date format that is shown in the card.
I know that grocy only supports the international date format yyyy mm dd, but i'm not used to it and always have to remind me of this. 

Thank you for your great work!

**Comment by zipitrik** [comment]
Hi,
If I can tag along on this subject, 

The card is great but I find the dates too hard to read (especially with long list of chores). 
I would personally love the option to remove all the dates all together and replace them with this kind of easy to read format :
- due; tomorrow
- due: in 2 days
- last tracked : 2 days ago
- last tracked : yesterday
- last tracked : today

I'm new to HA and was successful in achieving this results by doing the calculation in a template and creating custom sensors and then building a Frankenstein card replacing the dates with my results (in 2 days etc...).

I'm pretty sure I  didn't do it in the best way because I'm not a coder and new to HA but it would be so much easier to have it directly in your card :) 

In any case, like henneho said, **Thanks a lot for the great work**

**Comment by clarinetJWD** [comment]
I just made a new fork and pull request to this branch that addresses both of these. It uses your localization settings for the date format, and allows you to set a threshold below which all tasks will say "Due: In 2/3/4 Days".

Feel free to switch to my fork or wait for the pull request to be merged!

**Comment by zipitrik** [comment]
Thank you so much !! , This is great . And I love that each user can choose what work best for them

Now, If one day you have time to do the same for last tracked that would be great. 
Personally, just like the due date. last tracked: 18 days ago speak faster than a date....

In any case , thanks again the improvements are great.

**Comment by clarinetJWD** [comment]
I added this into the latest beta on my fork. A new variable use_due_in_days_for_past turns this on and off, and it'll show "Last Tracked: Today/Yesterday/4 Days Ago/Etc."

I'll pull request it here in a few days when I am sure there aren't any major bugs.

**Comment by clarinetJWD** [comment]
I 100% plan on continuing to make improvements like that. It's at a place
where it works perfectly for me, but I'm the kind of person who looks
basically everything and thinks "that should be an option." (My day job is
a UI/UX designer, so I love stuff like that)

More to come, for sure. And glad you're happy with it!
